INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (20,'Car','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',434723.0),
	 (46,'Mouse','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',71866.0),
	 (30,'Tuna','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',359373.0),
	 (10,'Pizza','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',127303.0),
	 (46,'Cheese','The Football Is Good For Training And Recreational Purposes',145230.0),
	 (1,'Sausages','The Football Is Good For Training And Recreational Purposes',109424.0),
	 (40,'Chips','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',30933.0),
	 (6,'Ball','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',377556.0),
	 (43,'Chair','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',134612.0),
	 (1,'Gloves','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',367625.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (42,'Salad','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',352879.0),
	 (39,'Computer','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',137206.0),
	 (13,'Towels','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',90114.0),
	 (36,'Gloves','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',469463.0),
	 (7,'Car','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',255296.0),
	 (47,'Tuna','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',485673.0),
	 (23,'Shoes','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',332325.0),
	 (17,'Chicken','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',93964.0),
	 (48,'Ball','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',265525.0),
	 (24,'Shirt','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',338765.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (11,'Soap','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',58939.0),
	 (34,'Cheese','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',489627.0),
	 (17,'Bacon','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',74944.0),
	 (17,'Pants','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',288204.0),
	 (18,'Car','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',73798.0),
	 (19,'Salad','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',113178.0),
	 (32,'Bike','The Football Is Good For Training And Recreational Purposes',405792.0),
	 (31,'Bike','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',439396.0),
	 (35,'Keyboard','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',465910.0),
	 (24,'Chips','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',422688.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (13,'Mouse','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',303868.0),
	 (24,'Soap','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',260285.0),
	 (36,'Soap','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',91670.0),
	 (6,'Tuna','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',172309.0),
	 (10,'Chair','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',60347.0),
	 (32,'Table','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',435847.0),
	 (37,'Shoes','The Football Is Good For Training And Recreational Purposes',294586.0),
	 (27,'Chair','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',390787.0),
	 (20,'Computer','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',62006.0),
	 (41,'Shoes','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',391496.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (38,'Soap','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',419634.0),
	 (42,'Gloves','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',496986.0),
	 (38,'Bike','The Football Is Good For Training And Recreational Purposes',354653.0),
	 (37,'Salad','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',94793.0),
	 (5,'Fish','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',126243.0),
	 (29,'Hat','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',257792.0),
	 (32,'Table','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',321290.0),
	 (21,'Chips','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',473530.0),
	 (40,'Gloves','The Football Is Good For Training And Recreational Purposes',277412.0),
	 (42,'Fish','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',125237.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (29,'Towels','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',383276.0),
	 (14,'Pants','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',284530.0),
	 (45,'Computer','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',407730.0),
	 (15,'Shirt','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',160846.0),
	 (25,'Hat','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',15206.0),
	 (21,'Pizza','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',462606.0),
	 (10,'Towels','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',110134.0),
	 (25,'Mouse','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',223518.0),
	 (14,'Cheese','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',241916.0),
	 (50,'Soap','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',252740.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (2,'Cheese','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',76685.0),
	 (36,'Cheese','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',298084.0),
	 (24,'Hat','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',152810.0),
	 (45,'Pizza','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',193263.0),
	 (28,'Salad','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',161601.0),
	 (47,'Pants','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',305313.0),
	 (24,'Chicken','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',20583.0),
	 (35,'Chair','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',13423.0),
	 (10,'Bike','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',251871.0),
	 (45,'Car','The Football Is Good For Training And Recreational Purposes',220633.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (47,'Shoes','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',498258.0),
	 (21,'Keyboard','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',44257.0),
	 (20,'Bacon','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',114999.0),
	 (9,'Soap','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',179847.0),
	 (9,'Pants','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',421035.0),
	 (27,'Shirt','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',225707.0),
	 (43,'Sausages','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',461168.0),
	 (43,'Pizza','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',415912.0),
	 (29,'Bike','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',321512.0),
	 (40,'Chair','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',445571.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (42,'Chips','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',439857.0),
	 (37,'Bike','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',307225.0),
	 (49,'Chair','The Football Is Good For Training And Recreational Purposes',376038.0),
	 (19,'Pizza','The Football Is Good For Training And Recreational Purposes',489132.0),
	 (15,'Car','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',228768.0),
	 (1,'Salad','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',286517.0),
	 (47,'Chicken','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',246204.0),
	 (17,'Cheese','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',126743.0),
	 (49,'Mouse','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',224004.0),
	 (3,'Fish','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',33388.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (42,'Soap','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',297501.0),
	 (37,'Gloves','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',128558.0),
	 (8,'Computer','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',266770.0),
	 (30,'Bike','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',273553.0),
	 (13,'Pizza','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',451121.0),
	 (37,'Towels','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',447939.0),
	 (41,'Chair','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',126808.0),
	 (47,'Tuna','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',356270.0),
	 (3,'Chicken','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',203990.0),
	 (14,'Chicken','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',468479.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (25,'Shoes','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',300901.0),
	 (20,'Pants','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',448561.0),
	 (33,'Car','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',243722.0),
	 (36,'Chips','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',198769.0),
	 (19,'Chicken','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',334394.0),
	 (17,'Car','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',370968.0),
	 (48,'Chair','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',206583.0),
	 (40,'Table','The Football Is Good For Training And Recreational Purposes',225435.0),
	 (45,'Car','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',161780.0),
	 (1,'Table','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',148505.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (6,'Soap','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',216627.0),
	 (21,'Cheese','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',441393.0),
	 (35,'Computer','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',221358.0),
	 (34,'Chair','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',269115.0),
	 (23,'Chips','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',484175.0),
	 (14,'Keyboard','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',474155.0),
	 (37,'Pants','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',352197.0),
	 (40,'Chair','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',442907.0),
	 (24,'Soap','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',209611.0),
	 (10,'Towels','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',269559.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (17,'Pants','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',206695.0),
	 (44,'Chicken','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',393287.0),
	 (46,'Ball','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',161999.0),
	 (27,'Gloves','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',263808.0),
	 (27,'Salad','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',368393.0),
	 (50,'Chips','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',173375.0),
	 (42,'Ball','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',56503.0),
	 (1,'Computer','The Football Is Good For Training And Recreational Purposes',497997.0),
	 (21,'Shoes','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',50162.0),
	 (27,'Gloves','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',18944.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (50,'Bacon','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',66321.0),
	 (37,'Car','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',414593.0),
	 (14,'Shoes','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',133354.0),
	 (37,'Ball','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',208229.0),
	 (28,'Tuna','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',195259.0),
	 (10,'Shoes','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',143265.0),
	 (7,'Cheese','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',483330.0),
	 (31,'Cheese','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',52971.0),
	 (34,'Gloves','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',387052.0),
	 (3,'Chips','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',155738.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (6,'Sausages','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',436013.0),
	 (46,'Fish','The Football Is Good For Training And Recreational Purposes',258354.0),
	 (28,'Fish','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',45098.0),
	 (50,'Pants','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',132694.0),
	 (37,'Car','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',244743.0),
	 (30,'Chicken','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',341168.0),
	 (34,'Soap','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',140134.0),
	 (33,'Computer','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',420810.0),
	 (40,'Tuna','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',82383.0),
	 (3,'Tuna','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',476903.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (3,'Bacon','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',332842.0),
	 (2,'Chair','The Football Is Good For Training And Recreational Purposes',412811.0),
	 (15,'Fish','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',16559.0),
	 (25,'Keyboard','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',58809.0),
	 (25,'Hat','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',293576.0),
	 (11,'Pants','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',116352.0),
	 (38,'Tuna','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',192536.0),
	 (2,'Hat','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',182166.0),
	 (33,'Keyboard','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',330149.0),
	 (36,'Shirt','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',294415.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (45,'Keyboard','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',180942.0),
	 (18,'Mouse','The Football Is Good For Training And Recreational Purposes',59523.0),
	 (18,'Ball','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',327334.0),
	 (42,'Cheese','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',36884.0),
	 (4,'Tuna','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',169111.0),
	 (25,'Shirt','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',315469.0),
	 (8,'Chair','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',413743.0),
	 (38,'Bacon','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',313323.0),
	 (37,'Salad','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',363319.0),
	 (28,'Hat','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',359757.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (18,'Gloves','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',485762.0),
	 (20,'Chair','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',234250.0),
	 (23,'Shoes','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',354624.0),
	 (3,'Ball','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',221436.0),
	 (36,'Sausages','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',302310.0),
	 (28,'Keyboard','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',424498.0),
	 (12,'Sausages','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',296920.0),
	 (43,'Tuna','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',480888.0),
	 (7,'Shirt','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',281160.0),
	 (22,'Car','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',294756.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (33,'Ball','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',370584.0),
	 (30,'Chicken','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',115662.0),
	 (20,'Sausages','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',101703.0),
	 (49,'Gloves','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',253789.0),
	 (24,'Chair','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',245976.0),
	 (28,'Table','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',248661.0),
	 (2,'Chicken','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',279702.0),
	 (27,'Pizza','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',213218.0),
	 (12,'Computer','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',383365.0),
	 (29,'Bacon','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',260745.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (31,'Sausages','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',392425.0),
	 (49,'Pants','The Football Is Good For Training And Recreational Purposes',26326.0),
	 (8,'Chicken','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',265516.0),
	 (13,'Soap','The Football Is Good For Training And Recreational Purposes',432431.0),
	 (5,'Bike','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',113247.0),
	 (33,'Bacon','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',118711.0),
	 (22,'Car','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',175674.0),
	 (18,'Chips','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',267051.0),
	 (24,'Chips','The Football Is Good For Training And Recreational Purposes',202552.0),
	 (23,'Chair','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',178789.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (7,'Mouse','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',391663.0),
	 (41,'Fish','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',220070.0),
	 (11,'Soap','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',146984.0),
	 (42,'Chips','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',28342.0),
	 (34,'Shoes','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',498363.0),
	 (2,'Shoes','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',147509.0),
	 (26,'Fish','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',218778.0),
	 (9,'Chips','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',362754.0),
	 (26,'Pizza','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',441800.0),
	 (46,'Keyboard','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',214182.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (1,'Mouse','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',42547.0),
	 (39,'Sausages','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',380490.0),
	 (47,'Chips','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',249340.0),
	 (10,'Pizza','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',286559.0),
	 (23,'Soap','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',186355.0),
	 (11,'Hat','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',169444.0),
	 (6,'Fish','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',82579.0),
	 (26,'Chair','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',356473.0),
	 (7,'Keyboard','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',402620.0),
	 (39,'Shirt','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',112798.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (18,'Gloves','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',74316.0),
	 (26,'Bike','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',86423.0),
	 (16,'Chicken','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',161621.0),
	 (36,'Ball','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',358440.0),
	 (50,'Keyboard','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',317716.0),
	 (14,'Chicken','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',102415.0),
	 (34,'Bacon','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',348885.0),
	 (29,'Towels','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',143688.0),
	 (41,'Mouse','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',275694.0),
	 (26,'Hat','The Football Is Good For Training And Recreational Purposes',490016.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (4,'Tuna','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',273368.0),
	 (20,'Tuna','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',323041.0),
	 (10,'Bacon','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',81405.0),
	 (40,'Car','The Football Is Good For Training And Recreational Purposes',287379.0),
	 (25,'Shoes','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',74902.0),
	 (17,'Pizza','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',173868.0),
	 (22,'Shirt','The Football Is Good For Training And Recreational Purposes',152514.0),
	 (47,'Pizza','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',215141.0),
	 (49,'Gloves','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',209207.0),
	 (2,'Towels','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',493623.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (40,'Towels','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',431642.0),
	 (48,'Car','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',363558.0),
	 (41,'Keyboard','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',284662.0),
	 (17,'Chicken','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',212539.0),
	 (1,'Salad','The Football Is Good For Training And Recreational Purposes',55620.0),
	 (22,'Keyboard','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',240554.0),
	 (38,'Salad','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',138707.0),
	 (43,'Gloves','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',251129.0),
	 (38,'Mouse','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',61467.0),
	 (12,'Fish','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',55612.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (21,'Pizza','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',333858.0),
	 (24,'Chicken','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',18429.0),
	 (39,'Shirt','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',85334.0),
	 (2,'Chips','New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',251111.0),
	 (8,'Pizza','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',215029.0),
	 (24,'Keyboard','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',50163.0),
	 (1,'Keyboard','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',44914.0),
	 (24,'Keyboard','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',254667.0),
	 (30,'Keyboard','The Football Is Good For Training And Recreational Purposes',222259.0),
	 (20,'Ball','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',226976.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (46,'Table','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',58702.0),
	 (23,'Mouse','The Football Is Good For Training And Recreational Purposes',453082.0),
	 (6,'Ball','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',475289.0),
	 (20,'Pizza','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',388334.0),
	 (14,'Car','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',324648.0),
	 (5,'Keyboard','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',365149.0),
	 (4,'Shoes','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',201013.0),
	 (8,'Towels','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',453441.0),
	 (28,'Tuna','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',306974.0),
	 (50,'Shirt','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',257144.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (41,'Salad','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',350702.0),
	 (9,'Shirt','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',186141.0),
	 (36,'Chicken','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',249690.0),
	 (17,'Gloves','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',38984.0),
	 (14,'Cheese','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',21362.0),
	 (35,'Car','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',465483.0),
	 (21,'Bike','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',312916.0),
	 (21,'Bacon','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',271994.0),
	 (1,'Bike','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',93562.0),
	 (38,'Cheese','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',135478.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (24,'Pants','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',397302.0),
	 (9,'Shirt','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',350444.0),
	 (28,'Mouse','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',213564.0),
	 (40,'Shoes','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',277242.0),
	 (16,'Computer','The Football Is Good For Training And Recreational Purposes',497140.0),
	 (27,'Tuna','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',149440.0),
	 (2,'Ball','Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',406056.0),
	 (12,'Fish','Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',462494.0),
	 (29,'Towels','Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',168076.0),
	 (5,'Tuna','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',324939.0);
INSERT INTO synapsis.products (product_category_id,name,description,price) VALUES
	 (22,'Sausages','Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',396845.0),
	 (17,'Pants','New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',462136.0),
	 (39,'Tuna','The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',392465.0),
	 (38,'Gloves','The Football Is Good For Training And Recreational Purposes',271968.0),
	 (21,'Keyboard','The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',451614.0),
	 (14,'Sausages','The Football Is Good For Training And Recreational Purposes',56246.0),
	 (11,'Chair','The Football Is Good For Training And Recreational Purposes',21397.0),
	 (37,'Chips','The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',192563.0),
	 (38,'Salad','The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',125142.0),
	 (29,'Tuna','The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',150049.0);
