name: Deploy
on:
  push:
    tags:        
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      - name: check code
        run: go vet main.go

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: anggasaputra/synapsis:${{RELEASE_VERSION}}